package com.example.app_challenge_meli.model.search

data class Producto(
    var accepts_mercadopago: Boolean? = false,
    var address: Address? = Address(),
    var attributes: List<Attribute>? = listOf(),
    var available_quantity: Int? = 0,
    var buying_mode: String? = "",
    var catalog_listing: Boolean? = false,
    var catalog_product_id: String? = "",
    var category_id: String? = "",
    var condition: String? = "",
    var currency_id: String? = "",
    var differential_pricing: DifferentialPricing? = DifferentialPricing(),
    var discounts: Any? = Any(),
    var domain_id: String? = "",
    var id: String? = "",
    var installments: Installments? = Installments(),
    var listing_type_id: String? = "",
    var match_score: Any? = Any(),
    var melicoin: Any? = Any(),
    var offer_score: Any? = Any(),
    var offer_share: Any? = Any(),
    var official_store_id: Int? = 0,
    var order_backend: Int? = 0,
    var original_price: Double? = 0.0,
    var permalink: String? = "",
    var price: Double? = 0.0,
    var prices: Prices? = Prices(),
    var sale_price: Any? = Any(),
    var seller: Seller? = Seller(),
    var seller_address: SellerAddress? = SellerAddress(),
    var shipping: Shipping? = Shipping(),
    var site_id: String? = "",
    var sold_quantity: Int? = 0,
    var stop_time: String? = "",
    var tags: List<String>? = listOf(),
    var thumbnail: String? = "",
    var thumbnail_id: String? = "",
    var title: String? = "",
    var use_thumbnail_id: Boolean? = false,
    var winner_item_id: Any? = Any()
)